query {
  findAll {
    ... on SimpleProductObject {
      size
      weight
      material
      product {
        name
        description
        sku
        salePrice
        costPrice
        promotionalPrice
        thumbnail
        productType {
          name
        }
      }
    }
    ... on VirtualProductObject {
      downloand_link
      product {
        name
        description
        sku
        salePrice
        costPrice
        promotionalPrice
        thumbnail
        productType {
          name
        }
      }
    }
  }
}
