query {
  findAll {
    ... on SimpleProductOutput {
      name
      description
      sku
      salePrice
      costPrice
      promotionalPrice
      thumbnail
      size
      weight
      material
      productType {
        name
      }
    }
  	... on VirtualProductOutput {
      name
      description
      sku
      salePrice
      costPrice
      promotionalPrice
      thumbnail
      downloadLink
      productType {
        name
      }
    }
  }	
}
