apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app-deployment
  namespace: mach-commerce-catalog
  labels:
    app: nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - image: deyvisonborges/mach-commerce-catalog:latest
          name: mach-commerce-catalog-container
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: nestjs-app
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-nodeport-service
  namespace: mach-commerce-catalog
spec:
  ports:
    - name: "nestjs-service-port"
      port: 3000
      targetPort: 3000
      nodePort: 30253
      protocol: TCP
  selector:
    app: nestjs-app
  type: NodePort
  
