apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplication-rs
  labels:
    app: aplicacao
    type: backend
spec:
  template:
    metadata:
      name: aplicacao-pod
      labels:
        app: aplicacao
        type: backend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      type: backend