query {
  findAllSimpleProduct {
    size
    weight
    material
    name
    description
    sku
    salePrice
    costPrice
    promotionalPrice
    thumbnail
    productType {
      name
    }
  }
}
