mutation {
  createVirtualProduct(input: {
		downloadLink: "/link"
    name: "Gift Card"
    description: "Free Fire Points"
    sku: "GIFT2NN31"
    salePrice: 9.90
    costPrice: 9.90
    promotionalPrice: 0.00
    thumbnail: "url-gift"
    productTypeId: "6fd5a854-3566-48d7-a053-ad534f9945f2"
  }){
    downloadLink
		productType {
      name
    }
    name
    description
    sku
    salePrice
    costPrice
    promotionalPrice
    thumbnail
  }
}
