# Create a simple product
mutation {
  createSimpleProduct(createSimpleProductInput: {
    images: [
      { name: "Image 001", description: "Image description", url: "image-url", productId: "12"}
      { name: "Image 001", description: "Image description", url: "image-url", productId: "12"}
    ]
    name: "Nome do Produto",
    description: "Descrição do Produto",
    sku: "SKU-123",
    salePrice: 50.00,
    costPrice: 30.00,
    promotionalPrice: 40.00,
    thumbnail: "url-da-imagem-thumbnail",
    type: "SIMPLE_PRODUCT",
    size: "Tamanho do Produto",
    weight: 1.5,
    material: "Material do Produto",
  }) {
    name
    description
    sku
    salePrice
    costPrice
    promotionalPrice
    thumbnail
    type
    size
    weight
    material
  }
}
